apiVersion: v1
kind: Pod
metadata:
  name: api
  labels:
    app: api
spec:
  containers:
  - name: api-pod
    image: thehaohcm/stockvn-backend-api:0.0.1-amd64
    ports:
    - containerPort: 3000
    env:
    - name: DB_HOST
      value: ""
    - name: DB_USER
      value: ""
    - name: DB_PASSWORD
      value: ""
    - name: DB_NAME
      value: ""
    - name: DB_PORT
      value: ""
