apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: thehaohcm/stockvn-frontend-ui:0.0.4-amd64
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /app/dist/config.json
              subPath: config.json
      volumes:
        - name: config-volume
          configMap:
            name: frontend-config
